# Generated by Django 3.2.9 on 2022-04-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_comment_rel',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='post_comment_rel',
            name='post_id',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post_Comment_Rel',
        ),
    ]
