# Generated by Django 3.2.9 on 2022-06-10 20:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_userprofileimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileImage',
            new_name='UserProfileImage2',
        ),
    ]
