# Generated by Django 3.2.9 on 2022-06-10 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220610_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PPImage',
        ),
    ]
